# Auto-generated: all valid Vietnamese syllables in ASCII (no diacritics)
# Total: 2422 syllables
VIET_SYLLABLES = {
    "a", "ac", "ach", "ai", "am", "an", "ang", "anh", "ao", "ap", "at", "au", "ay", "ba", "bac",
    "bach", "bai", "bam", "ban", "bang", "banh", "bao", "bap", "bat", "bau", "bay", "be", "bec",
    "bem", "ben", "beng", "beo", "bep", "bet", "bi", "bia", "bich", "biem", "bien", "bieng",
    "biep", "biet", "bieu", "bim", "bin", "binh", "bip", "bit", "biu", "bo", "boa", "boac",
    "boach", "boai", "boam", "boan", "boang", "boanh", "boap", "boat", "boay", "boc", "boe",
    "boem", "boen", "boet", "boi", "bom", "bon", "bong", "bop", "bot", "bu", "bua", "buai", "buan",
    "buang", "buat", "buay", "buc", "bui", "bum", "bun", "bung", "buoc", "buoi", "buom", "buon",
    "buong", "buot", "bup", "but", "buy", "buya", "buyen", "buynh", "buyt", "buyu", "by", "byem",
    "byen", "byet", "byeu", "ca", "cac", "cach", "cai", "cam", "can", "cang", "canh", "cao", "cap",
    "cat", "cau", "cay", "ce", "cec", "cem", "cen", "ceng", "ceo", "cep", "cet", "cha", "chac",
    "chach", "chai", "cham", "chan", "chang", "chanh", "chao", "chap", "chat", "chau", "chay",
    "che", "chec", "chem", "chen", "cheng", "cheo", "chep", "chet", "chi", "chia", "chich",
    "chiem", "chien", "chieng", "chiep", "chiet", "chieu", "chim", "chin", "chinh", "chip", "chit",
    "chiu", "cho", "choa", "choac", "choach", "choai", "choam", "choan", "choang", "choanh",
    "choap", "choat", "choay", "choc", "choe", "choem", "choen", "choet", "choi", "chom", "chon",
    "chong", "chop", "chot", "chu", "chua", "chuai", "chuan", "chuang", "chuat", "chuay", "chuc",
    "chui", "chum", "chun", "chung", "chuoc", "chuoi", "chuom", "chuon", "chuong", "chuot", "chup",
    "chut", "chuy", "chuya", "chuyen", "chuynh", "chuyt", "chuyu", "chy", "chyem", "chyen",
    "chyet", "chyeu", "ci", "cia", "cich", "ciem", "cien", "cieng", "ciep", "ciet", "cieu", "cim",
    "cin", "cinh", "cip", "cit", "ciu", "co", "coa", "coac", "coach", "coai", "coam", "coan",
    "coang", "coanh", "coap", "coat", "coay", "coc", "coe", "coem", "coen", "coet", "coi", "com",
    "con", "cong", "cop", "cot", "cu", "cua", "cuai", "cuan", "cuang", "cuat", "cuay", "cuc",
    "cui", "cum", "cun", "cung", "cuoc", "cuoi", "cuom", "cuon", "cuong", "cuot", "cup", "cut",
    "cuy", "cuya", "cuyen", "cuynh", "cuyt", "cuyu", "cy", "cyem", "cyen", "cyet", "cyeu", "da",
    "dac", "dach", "dai", "dam", "dan", "dang", "danh", "dao", "dap", "dat", "dau", "day", "de",
    "dec", "dem", "den", "deng", "deo", "dep", "det", "di", "dia", "dich", "diem", "dien", "dieng",
    "diep", "diet", "dieu", "dim", "din", "dinh", "dip", "dit", "diu", "do", "doa", "doac",
    "doach", "doai", "doam", "doan", "doang", "doanh", "doap", "doat", "doay", "doc", "doe",
    "doem", "doen", "doet", "doi", "dom", "don", "dong", "dop", "dot", "du", "dua", "duai", "duan",
    "duang", "duat", "duay", "duc", "dui", "dum", "dun", "dung", "duoc", "duoi", "duom", "duon",
    "duong", "duot", "dup", "dut", "duy", "duya", "duyen", "duynh", "duyt", "duyu", "dy", "dyem",
    "dyen", "dyet", "dyeu", "ec", "em", "en", "eng", "eo", "ep", "et", "ga", "gac", "gach", "gai",
    "gam", "gan", "gang", "ganh", "gao", "gap", "gat", "gau", "gay", "ge", "gec", "gem", "gen",
    "geng", "geo", "gep", "get", "gha", "ghac", "ghach", "ghai", "gham", "ghan", "ghang", "ghanh",
    "ghao", "ghap", "ghat", "ghau", "ghay", "ghe", "ghec", "ghem", "ghen", "gheng", "gheo", "ghep",
    "ghet", "ghi", "ghia", "ghich", "ghiem", "ghien", "ghieng", "ghiep", "ghiet", "ghieu", "ghim",
    "ghin", "ghinh", "ghip", "ghit", "ghiu", "gho", "ghoa", "ghoac", "ghoach", "ghoai", "ghoam",
    "ghoan", "ghoang", "ghoanh", "ghoap", "ghoat", "ghoay", "ghoc", "ghoe", "ghoem", "ghoen",
    "ghoet", "ghoi", "ghom", "ghon", "ghong", "ghop", "ghot", "ghu", "ghua", "ghuai", "ghuan",
    "ghuang", "ghuat", "ghuay", "ghuc", "ghui", "ghum", "ghun", "ghung", "ghuoc", "ghuoi", "ghuom",
    "ghuon", "ghuong", "ghuot", "ghup", "ghut", "ghuy", "ghuya", "ghuyen", "ghuynh", "ghuyt",
    "ghuyu", "ghy", "ghyem", "ghyen", "ghyet", "ghyeu", "gi", "gia", "giac", "giach", "giai",
    "giam", "gian", "giang", "gianh", "giao", "giap", "giat", "giau", "giay", "gich", "gie",
    "giec", "giem", "gien", "gieng", "gieo", "giep", "giet", "gieu", "gii", "giia", "giich",
    "giiem", "giien", "giieng", "giiep", "giiet", "giieu", "giim", "giin", "giinh", "giip", "giit",
    "giiu", "gim", "gin", "ginh", "gio", "gioa", "gioac", "gioach", "gioai", "gioam", "gioan",
    "gioang", "gioanh", "gioap", "gioat", "gioay", "gioc", "gioe", "gioem", "gioen", "gioet",
    "gioi", "giom", "gion", "giong", "giop", "giot", "gip", "git", "giu", "giua", "giuai", "giuan",
    "giuang", "giuat", "giuay", "giuc", "giui", "gium", "giun", "giung", "giuoc", "giuoi", "giuom",
    "giuon", "giuong", "giuot", "giup", "giut", "giuy", "giuya", "giuyen", "giuynh", "giuyt",
    "giuyu", "giy", "giyem", "giyen", "giyet", "giyeu", "go", "goa", "goac", "goach", "goai",
    "goam", "goan", "goang", "goanh", "goap", "goat", "goay", "goc", "goe", "goem", "goen", "goet",
    "goi", "gom", "gon", "gong", "gop", "got", "gu", "gua", "guai", "guan", "guang", "guat",
    "guay", "guc", "gui", "gum", "gun", "gung", "guoc", "guoi", "guom", "guon", "guong", "guot",
    "gup", "gut", "guy", "guya", "guyen", "guynh", "guyt", "guyu", "gy", "gyem", "gyen", "gyet",
    "gyeu", "ha", "hac", "hach", "hai", "ham", "han", "hang", "hanh", "hao", "hap", "hat", "hau",
    "hay", "he", "hec", "hem", "hen", "heng", "heo", "hep", "het", "hi", "hia", "hich", "hiem",
    "hien", "hieng", "hiep", "hiet", "hieu", "him", "hin", "hinh", "hip", "hit", "hiu", "ho",
    "hoa", "hoac", "hoach", "hoai", "hoam", "hoan", "hoang", "hoanh", "hoap", "hoat", "hoay",
    "hoc", "hoe", "hoem", "hoen", "hoet", "hoi", "hom", "hon", "hong", "hop", "hot", "hu", "hua",
    "huai", "huan", "huang", "huat", "huay", "huc", "hui", "hum", "hun", "hung", "huoc", "huoi",
    "huom", "huon", "huong", "huot", "hup", "hut", "huy", "huya", "huyen", "huynh", "huyt", "huyu",
    "hy", "hyem", "hyen", "hyet", "hyeu", "i", "ia", "ich", "iem", "ien", "ieng", "iep", "iet",
    "ieu", "im", "in", "inh", "ip", "it", "iu", "ka", "kac", "kach", "kai", "kam", "kan", "kang",
    "kanh", "kao", "kap", "kat", "kau", "kay", "ke", "kec", "kem", "ken", "keng", "keo", "kep",
    "ket", "kha", "khac", "khach", "khai", "kham", "khan", "khang", "khanh", "khao", "khap",
    "khat", "khau", "khay", "khe", "khec", "khem", "khen", "kheng", "kheo", "khep", "khet", "khi",
    "khia", "khich", "khiem", "khien", "khieng", "khiep", "khiet", "khieu", "khim", "khin",
    "khinh", "khip", "khit", "khiu", "kho", "khoa", "khoac", "khoach", "khoai", "khoam", "khoan",
    "khoang", "khoanh", "khoap", "khoat", "khoay", "khoc", "khoe", "khoem", "khoen", "khoet",
    "khoi", "khom", "khon", "khong", "khop", "khot", "khu", "khua", "khuai", "khuan", "khuang",
    "khuat", "khuay", "khuc", "khui", "khum", "khun", "khung", "khuoc", "khuoi", "khuom", "khuon",
    "khuong", "khuot", "khup", "khut", "khuy", "khuya", "khuyen", "khuynh", "khuyt", "khuyu",
    "khy", "khyem", "khyen", "khyet", "khyeu", "ki", "kia", "kich", "kiem", "kien", "kieng",
    "kiep", "kiet", "kieu", "kim", "kin", "kinh", "kip", "kit", "kiu", "ko", "koa", "koac",
    "koach", "koai", "koam", "koan", "koang", "koanh", "koap", "koat", "koay", "koc", "koe",
    "koem", "koen", "koet", "koi", "kom", "kon", "kong", "kop", "kot", "ku", "kua", "kuai", "kuan",
    "kuang", "kuat", "kuay", "kuc", "kui", "kum", "kun", "kung", "kuoc", "kuoi", "kuom", "kuon",
    "kuong", "kuot", "kup", "kut", "kuy", "kuya", "kuyen", "kuynh", "kuyt", "kuyu", "ky", "kyem",
    "kyen", "kyet", "kyeu", "la", "lac", "lach", "lai", "lam", "lan", "lang", "lanh", "lao", "lap",
    "lat", "lau", "lay", "le", "lec", "lem", "len", "leng", "leo", "lep", "let", "li", "lia",
    "lich", "liem", "lien", "lieng", "liep", "liet", "lieu", "lim", "lin", "linh", "lip", "lit",
    "liu", "lo", "loa", "loac", "loach", "loai", "loam", "loan", "loang", "loanh", "loap", "loat",
    "loay", "loc", "loe", "loem", "loen", "loet", "loi", "lom", "lon", "long", "lop", "lot", "lu",
    "lua", "luai", "luan", "luang", "luat", "luay", "luc", "lui", "lum", "lun", "lung", "luoc",
    "luoi", "luom", "luon", "luong", "luot", "lup", "lut", "luy", "luya", "luyen", "luynh", "luyt",
    "luyu", "ly", "lyem", "lyen", "lyet", "lyeu", "ma", "mac", "mach", "mai", "mam", "man", "mang",
    "manh", "mao", "map", "mat", "mau", "may", "me", "mec", "mem", "men", "meng", "meo", "mep",
    "met", "mi", "mia", "mich", "miem", "mien", "mieng", "miep", "miet", "mieu", "mim", "min",
    "minh", "mip", "mit", "miu", "mo", "moa", "moac", "moach", "moai", "moam", "moan", "moang",
    "moanh", "moap", "moat", "moay", "moc", "moe", "moem", "moen", "moet", "moi", "mom", "mon",
    "mong", "mop", "mot", "mu", "mua", "muai", "muan", "muang", "muat", "muay", "muc", "mui",
    "mum", "mun", "mung", "muoc", "muoi", "muom", "muon", "muong", "muot", "mup", "mut", "muy",
    "muya", "muyen", "muynh", "muyt", "muyu", "my", "myem", "myen", "myet", "myeu", "na", "nac",
    "nach", "nai", "nam", "nan", "nang", "nanh", "nao", "nap", "nat", "nau", "nay", "ne", "nec",
    "nem", "nen", "neng", "neo", "nep", "net", "nga", "ngac", "ngach", "ngai", "ngam", "ngan",
    "ngang", "nganh", "ngao", "ngap", "ngat", "ngau", "ngay", "nge", "ngec", "ngem", "ngen",
    "ngeng", "ngeo", "ngep", "nget", "ngha", "nghac", "nghach", "nghai", "ngham", "nghan",
    "nghang", "nghanh", "nghao", "nghap", "nghat", "nghau", "nghay", "nghe", "nghec", "nghem",
    "nghen", "ngheng", "ngheo", "nghep", "nghet", "nghi", "nghia", "nghich", "nghiem", "nghien",
    "nghieng", "nghiep", "nghiet", "nghieu", "nghim", "nghin", "nghinh", "nghip", "nghit", "nghiu",
    "ngho", "nghoa", "nghoac", "nghoach", "nghoai", "nghoam", "nghoan", "nghoang", "nghoanh",
    "nghoap", "nghoat", "nghoay", "nghoc", "nghoe", "nghoem", "nghoen", "nghoet", "nghoi", "nghom",
    "nghon", "nghong", "nghop", "nghot", "nghu", "nghua", "nghuai", "nghuan", "nghuang", "nghuat",
    "nghuay", "nghuc", "nghui", "nghum", "nghun", "nghung", "nghuoc", "nghuoi", "nghuom", "nghuon",
    "nghuong", "nghuot", "nghup", "nghut", "nghuy", "nghuya", "nghuyen", "nghuynh", "nghuyt",
    "nghuyu", "nghy", "nghyem", "nghyen", "nghyet", "nghyeu", "ngi", "ngia", "ngich", "ngiem",
    "ngien", "ngieng", "ngiep", "ngiet", "ngieu", "ngim", "ngin", "nginh", "ngip", "ngit", "ngiu",
    "ngo", "ngoa", "ngoac", "ngoach", "ngoai", "ngoam", "ngoan", "ngoang", "ngoanh", "ngoap",
    "ngoat", "ngoay", "ngoc", "ngoe", "ngoem", "ngoen", "ngoet", "ngoi", "ngom", "ngon", "ngong",
    "ngop", "ngot", "ngu", "ngua", "nguai", "nguan", "nguang", "nguat", "nguay", "nguc", "ngui",
    "ngum", "ngun", "ngung", "nguoc", "nguoi", "nguom", "nguon", "nguong", "nguot", "ngup", "ngut",
    "nguy", "nguya", "nguyen", "nguynh", "nguyt", "nguyu", "ngy", "ngyem", "ngyen", "ngyet",
    "ngyeu", "nha", "nhac", "nhach", "nhai", "nham", "nhan", "nhang", "nhanh", "nhao", "nhap",
    "nhat", "nhau", "nhay", "nhe", "nhec", "nhem", "nhen", "nheng", "nheo", "nhep", "nhet", "nhi",
    "nhia", "nhich", "nhiem", "nhien", "nhieng", "nhiep", "nhiet", "nhieu", "nhim", "nhin",
    "nhinh", "nhip", "nhit", "nhiu", "nho", "nhoa", "nhoac", "nhoach", "nhoai", "nhoam", "nhoan",
    "nhoang", "nhoanh", "nhoap", "nhoat", "nhoay", "nhoc", "nhoe", "nhoem", "nhoen", "nhoet",
    "nhoi", "nhom", "nhon", "nhong", "nhop", "nhot", "nhu", "nhua", "nhuai", "nhuan", "nhuang",
    "nhuat", "nhuay", "nhuc", "nhui", "nhum", "nhun", "nhung", "nhuoc", "nhuoi", "nhuom", "nhuon",
    "nhuong", "nhuot", "nhup", "nhut", "nhuy", "nhuya", "nhuyen", "nhuynh", "nhuyt", "nhuyu",
    "nhy", "nhyem", "nhyen", "nhyet", "nhyeu", "ni", "nia", "nich", "niem", "nien", "nieng",
    "niep", "niet", "nieu", "nim", "nin", "ninh", "nip", "nit", "niu", "no", "noa", "noac",
    "noach", "noai", "noam", "noan", "noang", "noanh", "noap", "noat", "noay", "noc", "noe",
    "noem", "noen", "noet", "noi", "nom", "non", "nong", "nop", "not", "nu", "nua", "nuai", "nuan",
    "nuang", "nuat", "nuay", "nuc", "nui", "num", "nun", "nung", "nuoc", "nuoi", "nuom", "nuon",
    "nuong", "nuot", "nup", "nut", "nuy", "nuya", "nuyen", "nuynh", "nuyt", "nuyu", "ny", "nyem",
    "nyen", "nyet", "nyeu", "o", "oa", "oac", "oach", "oai", "oam", "oan", "oang", "oanh", "oap",
    "oat", "oay", "oc", "oe", "oem", "oen", "oet", "oi", "om", "on", "ong", "op", "ot", "pa",
    "pac", "pach", "pai", "pam", "pan", "pang", "panh", "pao", "pap", "pat", "pau", "pay", "pe",
    "pec", "pem", "pen", "peng", "peo", "pep", "pet", "pha", "phac", "phach", "phai", "pham",
    "phan", "phang", "phanh", "phao", "phap", "phat", "phau", "phay", "phe", "phec", "phem",
    "phen", "pheng", "pheo", "phep", "phet", "phi", "phia", "phich", "phiem", "phien", "phieng",
    "phiep", "phiet", "phieu", "phim", "phin", "phinh", "phip", "phit", "phiu", "pho", "phoa",
    "phoac", "phoach", "phoai", "phoam", "phoan", "phoang", "phoanh", "phoap", "phoat", "phoay",
    "phoc", "phoe", "phoem", "phoen", "phoet", "phoi", "phom", "phon", "phong", "phop", "phot",
    "phu", "phua", "phuai", "phuan", "phuang", "phuat", "phuay", "phuc", "phui", "phum", "phun",
    "phung", "phuoc", "phuoi", "phuom", "phuon", "phuong", "phuot", "phup", "phut", "phuy",
    "phuya", "phuyen", "phuynh", "phuyt", "phuyu", "phy", "phyem", "phyen", "phyet", "phyeu", "pi",
    "pia", "pich", "piem", "pien", "pieng", "piep", "piet", "pieu", "pim", "pin", "pinh", "pip",
    "pit", "piu", "po", "poa", "poac", "poach", "poai", "poam", "poan", "poang", "poanh", "poap",
    "poat", "poay", "poc", "poe", "poem", "poen", "poet", "poi", "pom", "pon", "pong", "pop",
    "pot", "pu", "pua", "puai", "puan", "puang", "puat", "puay", "puc", "pui", "pum", "pun",
    "pung", "puoc", "puoi", "puom", "puon", "puong", "puot", "pup", "put", "puy", "puya", "puyen",
    "puynh", "puyt", "puyu", "py", "pyem", "pyen", "pyet", "pyeu", "qua", "quac", "quach", "quai",
    "quam", "quan", "quang", "quanh", "quao", "quap", "quat", "quau", "quay", "que", "quec",
    "quem", "quen", "queng", "queo", "quep", "quet", "qui", "quia", "quich", "quiem", "quien",
    "quieng", "quiep", "quiet", "quieu", "quim", "quin", "quinh", "quip", "quit", "quiu", "quo",
    "quoa", "quoac", "quoach", "quoai", "quoam", "quoan", "quoang", "quoanh", "quoap", "quoat",
    "quoay", "quoc", "quoe", "quoem", "quoen", "quoet", "quoi", "quom", "quon", "quong", "quop",
    "quot", "quu", "quua", "quuai", "quuan", "quuang", "quuat", "quuay", "quuc", "quui", "quum",
    "quun", "quung", "quuoc", "quuoi", "quuom", "quuon", "quuong", "quuot", "quup", "quut", "quuy",
    "quuya", "quuyen", "quuynh", "quuyt", "quuyu", "quy", "quyem", "quyen", "quyet", "quyeu", "ra",
    "rac", "rach", "rai", "ram", "ran", "rang", "ranh", "rao", "rap", "rat", "rau", "ray", "re",
    "rec", "rem", "ren", "reng", "reo", "rep", "ret", "ri", "ria", "rich", "riem", "rien", "rieng",
    "riep", "riet", "rieu", "rim", "rin", "rinh", "rip", "rit", "riu", "ro", "roa", "roac",
    "roach", "roai", "roam", "roan", "roang", "roanh", "roap", "roat", "roay", "roc", "roe",
    "roem", "roen", "roet", "roi", "rom", "ron", "rong", "rop", "rot", "ru", "rua", "ruai", "ruan",
    "ruang", "ruat", "ruay", "ruc", "rui", "rum", "run", "rung", "ruoc", "ruoi", "ruom", "ruon",
    "ruong", "ruot", "rup", "rut", "ruy", "ruya", "ruyen", "ruynh", "ruyt", "ruyu", "ry", "ryem",
    "ryen", "ryet", "ryeu", "sa", "sac", "sach", "sai", "sam", "san", "sang", "sanh", "sao", "sap",
    "sat", "sau", "say", "se", "sec", "sem", "sen", "seng", "seo", "sep", "set", "si", "sia",
    "sich", "siem", "sien", "sieng", "siep", "siet", "sieu", "sim", "sin", "sinh", "sip", "sit",
    "siu", "so", "soa", "soac", "soach", "soai", "soam", "soan", "soang", "soanh", "soap", "soat",
    "soay", "soc", "soe", "soem", "soen", "soet", "soi", "som", "son", "song", "sop", "sot", "su",
    "sua", "suai", "suan", "suang", "suat", "suay", "suc", "sui", "sum", "sun", "sung", "suoc",
    "suoi", "suom", "suon", "suong", "suot", "sup", "sut", "suy", "suya", "suyen", "suynh", "suyt",
    "suyu", "sy", "syem", "syen", "syet", "syeu", "ta", "tac", "tach", "tai", "tam", "tan", "tang",
    "tanh", "tao", "tap", "tat", "tau", "tay", "te", "tec", "tem", "ten", "teng", "teo", "tep",
    "tet", "tha", "thac", "thach", "thai", "tham", "than", "thang", "thanh", "thao", "thap",
    "that", "thau", "thay", "the", "thec", "them", "then", "theng", "theo", "thep", "thet", "thi",
    "thia", "thich", "thiem", "thien", "thieng", "thiep", "thiet", "thieu", "thim", "thin",
    "thinh", "thip", "thit", "thiu", "tho", "thoa", "thoac", "thoach", "thoai", "thoam", "thoan",
    "thoang", "thoanh", "thoap", "thoat", "thoay", "thoc", "thoe", "thoem", "thoen", "thoet",
    "thoi", "thom", "thon", "thong", "thop", "thot", "thu", "thua", "thuai", "thuan", "thuang",
    "thuat", "thuay", "thuc", "thui", "thum", "thun", "thung", "thuoc", "thuoi", "thuom", "thuon",
    "thuong", "thuot", "thup", "thut", "thuy", "thuya", "thuyen", "thuynh", "thuyt", "thuyu",
    "thy", "thyem", "thyen", "thyet", "thyeu", "ti", "tia", "tich", "tiem", "tien", "tieng",
    "tiep", "tiet", "tieu", "tim", "tin", "tinh", "tip", "tit", "tiu", "to", "toa", "toac",
    "toach", "toai", "toam", "toan", "toang", "toanh", "toap", "toat", "toay", "toc", "toe",
    "toem", "toen", "toet", "toi", "tom", "ton", "tong", "top", "tot", "tra", "trac", "trach",
    "trai", "tram", "tran", "trang", "tranh", "trao", "trap", "trat", "trau", "tray", "tre",
    "trec", "trem", "tren", "treng", "treo", "trep", "tret", "tri", "tria", "trich", "triem",
    "trien", "trieng", "triep", "triet", "trieu", "trim", "trin", "trinh", "trip", "trit", "triu",
    "tro", "troa", "troac", "troach", "troai", "troam", "troan", "troang", "troanh", "troap",
    "troat", "troay", "troc", "troe", "troem", "troen", "troet", "troi", "trom", "tron", "trong",
    "trop", "trot", "tru", "trua", "truai", "truan", "truang", "truat", "truay", "truc", "trui",
    "trum", "trun", "trung", "truoc", "truoi", "truom", "truon", "truong", "truot", "trup", "trut",
    "truy", "truya", "truyen", "truynh", "truyt", "truyu", "try", "tryem", "tryen", "tryet",
    "tryeu", "tu", "tua", "tuai", "tuan", "tuang", "tuat", "tuay", "tuc", "tui", "tum", "tun",
    "tung", "tuoc", "tuoi", "tuom", "tuon", "tuong", "tuot", "tup", "tut", "tuy", "tuya", "tuyen",
    "tuynh", "tuyt", "tuyu", "ty", "tyem", "tyen", "tyet", "tyeu", "u", "ua", "uai", "uan", "uang",
    "uat", "uay", "uc", "ui", "um", "un", "ung", "uoc", "uoi", "uom", "uon", "uong", "uot", "up",
    "ut", "uy", "uya", "uyen", "uynh", "uyt", "uyu", "va", "vac", "vach", "vai", "vam", "van",
    "vang", "vanh", "vao", "vap", "vat", "vau", "vay", "ve", "vec", "vem", "ven", "veng", "veo",
    "vep", "vet", "vi", "via", "vich", "viem", "vien", "vieng", "viep", "viet", "vieu", "vim",
    "vin", "vinh", "vip", "vit", "viu", "vo", "voa", "voac", "voach", "voai", "voam", "voan",
    "voang", "voanh", "voap", "voat", "voay", "voc", "voe", "voem", "voen", "voet", "voi", "vom",
    "von", "vong", "vop", "vot", "vu", "vua", "vuai", "vuan", "vuang", "vuat", "vuay", "vuc",
    "vui", "vum", "vun", "vung", "vuoc", "vuoi", "vuom", "vuon", "vuong", "vuot", "vup", "vut",
    "vuy", "vuya", "vuyen", "vuynh", "vuyt", "vuyu", "vy", "vyem", "vyen", "vyet", "vyeu", "xa",
    "xac", "xach", "xai", "xam", "xan", "xang", "xanh", "xao", "xap", "xat", "xau", "xay", "xe",
    "xec", "xem", "xen", "xeng", "xeo", "xep", "xet", "xi", "xia", "xich", "xiem", "xien", "xieng",
    "xiep", "xiet", "xieu", "xim", "xin", "xinh", "xip", "xit", "xiu", "xo", "xoa", "xoac",
    "xoach", "xoai", "xoam", "xoan", "xoang", "xoanh", "xoap", "xoat", "xoay", "xoc", "xoe",
    "xoem", "xoen", "xoet", "xoi", "xom", "xon", "xong", "xop", "xot", "xu", "xua", "xuai", "xuan",
    "xuang", "xuat", "xuay", "xuc", "xui", "xum", "xun", "xung", "xuoc", "xuoi", "xuom", "xuon",
    "xuong", "xuot", "xup", "xut", "xuy", "xuya", "xuyen", "xuynh", "xuyt", "xuyu", "xy", "xyem",
    "xyen", "xyet", "xyeu", "y", "yem", "yen", "yet", "yeu"
}
